### ISSUE TITLE
No longer supported soon

### ISSUE THREAD

**Issue by gabriel-vanca** [matthizou/github-show-avatars#7]
`This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.`

![image](https://github.com/user-attachments/assets/01614f5a-f502-4c58-8157-037d1b0c3198)

**Comment by matthizou** [comment]
Fixed (the extension needed to be migrated from manifest V2 to V3) 

![CleanShot 2024-12-03 at 10 51 47](https://github.com/user-attachments/assets/f385c98e-f647-46a0-897a-5adf06cfa043)
